
spring:
  profiles:
    active: dev

logging:
  level:
    com:
      bhojrajCreation:
        journalApp: DEBUG


apiKey:
  weather: 73a478310b97aac7d49ce3d8b64f5782
  quote: A2Zqg0I+w4VkIZEWv3PgDw==cqYpwaZZN9jlH5Se